Portfolio/portfolio/urls.py
from django.urls import path

from . import views

app_name = 'portfoilo'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('project/twitterpubhealth/', views.TwitterPubHealthView.as_view(), name='twitterpubhealth'),
    path('project/stagesourcecensus/', views.StageSourceCensusView.as_view(), name='stagesourcecensus'),
    path('project/transpop/', views.TransPopView.as_view(), name='transpop'),
    path('project/<str:project_shortname>/', views.ProjectView.as_view(), name='project'),
]

Portfolio/portfolio_site/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('portfolio.urls')),
    path('admin/', admin.site.urls),
]

Portfolio/portfolio/models.py
from django.db import models

# Create your models here.

class Company(models.Model):
    company_name = models.CharField(max_length=500)
    def __str__(self):
        return self.company_name

class Department(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    department_name = models.CharField(max_length=500)
    def __str__(self):
        return self.department_name

class Job(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    job_name = models.CharField(max_length=500)
    start_date = models.DateField()
    end_date = models.DateField()
    current_job = models.BooleanField()
    projects_only = models.BooleanField()
    display_order = models.IntegerField()
    def __str__(self):
        return self.job_name
    

class Responsibility(models.Model):
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    responsibility_name = models.CharField(max_length=200)
    description = models.CharField(max_length=2000)
    def __str__(self):
        return self.description

class Project(models.Model):
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    project_name = models.CharField(max_length=200)
    project_shortname = models.CharField(max_length=20, unique=True)
    description = models.TextField(max_length=2000)
    short_description = models.CharField(max_length=500)
    outcome = models.CharField(max_length=2000)
    timeline = models.CharField(max_length=200)
    languages = models.CharField(max_length=300)
    display_order = models.IntegerField()
    link = models.URLField()
    def __str__(self):
        return self.project_name

Portfolio/portfolio/views.py
from pickle import TRUE
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Project, Job, Responsibility

class IndexView(generic.ListView):
    template_name = 'portfolio/index.html'
    context_object_name = 'latest_project_list'

    def get_queryset(self):
        return Project.objects.all().order_by("display_order")
    
    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['jobs'] = Job.objects.filter(projects_only = False).order_by("display_order")
        context['current_jobs'] = Job.objects.filter(current_job=True)
        context['current_jobs'] = context['current_jobs'].filter(projects_only=False)
        context['responsibilities'] = Responsibility.objects.all()
        context['spc_responsibilities'] = Responsibility.objects.filter(job__id=1)
        context['apc_responsibilities'] = Responsibility.objects.filter(job__id=2)
        context['da_responsibilities'] = Responsibility.objects.filter(job__id=3)
        return context

class ProjectView(generic.DetailView):
    model = Project
    template_name = 'portfolio/project.html'

    def get_object(self):
        self.project = get_object_or_404(Project, project_shortname__exact=self.kwargs['project_shortname'])
        return Project.objects.filter(id=self.project.id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['project'] = self.project
        return context

class TwitterPubHealthView(generic.DetailView):
    model = Project
    template_name = 'portfolio/twitterpubhealth.html'

    def get_object(self):
        self.project = get_object_or_404(Project, project_shortname__exact='twitterpubhealth')
        return Project.objects.filter(id=self.project.id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['project'] = self.project
        return context

class StageSourceCensusView(generic.DetailView):
    model = Project
    template_name = 'portfolio/stagesourcecensus.html'

    def get_object(self):
        self.project = get_object_or_404(Project, project_shortname__exact='stagesourcecensus')
        return Project.objects.filter(id=self.project.id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['project'] = self.project
        return context

class TransPopView(generic.DetailView):
    model = Project
    template_name = 'portfolio/transpop.html'

    def get_object(self):
        self.project = get_object_or_404(Project, project_shortname__exact='transpop')
        return Project.objects.filter(id=self.project.id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['project'] = self.project
        return context

Portfolio/portfolio/templates/portfolio/index.html
{% extends "base.html" %}

{% load static %}

{% block title %}Olivia McCargar | Portfolio{% endblock %}

{% block stylesheets %}
<!--<link rel="stylesheet" href="{% static 'portfolio/style/cover.css' %}">-->
{% endblock %}

{% block bodyclasses %}style="position: relative;" data-bs-spy="scroll" data-bs-target="#primary-navbar"{% endblock %}

{% block content %}
<nav id="primary-navbar" class="navbar sticky-top bg-light px-3">
  <ul class="nav nav-pills">
    <li class="nav-item">
      <a class="nav-link" href="#aboutme">About</a>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#projects" role="button" aria-expanded="false">Projects</a>
      <ul class="dropdown-menu">
        <li><a class="dropdown-item" href="#projects">Projects Overview</a></li>
        <li><hr class="dropdown-divider"></li>
        {% for project in latest_project_list %}
        <li><a class="dropdown-item" href="{% url 'portfoilo:project' project.project_shortname %}">{{project.project_name}}</a></li>
        {% endfor %}
      </ul>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#resume">Resume</a>
    </li>
  </ul>
  <a class="navbar-brand" href="/">OKM</a>
</nav>
<div id="aboutme" class="p-4" style="width:100%; height:10px;"></div>
<div class="p-5 min-vh-100 d-inline-block">
  <h3>About Me</h3>
  <div class="row">
    <div class="col-3">
      <div class="headshot mb-2">
        <img class="rounded" src="{% static 'images/liv_headshot.png' %}" alt="Headshot of Olivia">
      </div>
      <div class="container mb-2" style="text-align: center;">
        <a href="{% static 'documents/Olivia McCargar Resume 2022.pdf' %}" class="m-auto btn btn-primary">Download Resume</a>
      </div>
    </div>
    <div class="col-9">
      <p>I am actively looking for the right company for me.</p>
      <p>I am a long time freelance graphic designer and web developer turned engineer. Over the last several years I have completed my Masters of Science in Computer Science with a focus on applied data analytics, making me an ideal data engineer for any team.</p>
      <p>My approach to solving problems is by diving in, getting my hands dirty, making mistakes, and asking for help. I'm a natural leader, a problem solver, and have an affinity for statistics.</p>
      <div class="contact">
        <h5>Contact</h5>
        <p>
          Email: <a href="mailto:OliviaMcCargar@gmail.com">OliviaMcCargar@gmail.com</a> </br>
          Github: <a href="https://github.com/OliviaMcCargar/">https://github.com/OliviaMcCargar/</a> </br>
          Linkedin: <a href="https://www.linkedin.com/in/olivia-mccargar/">https://www.linkedin.com/in/olivia-mccargar/</a>
        </p>
      </div>
      
      <h5>Current Roles</h5>
      {% for job in current_jobs %}
      <div class="job_desc">
        <p class="location">{{ job.company }}: {{ job.department }}</p>
        <p class="title">{{ job.job_name }}</p>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
<div id="projects" class="p-4" style="width:100%; height:10px;"></div>
<div class="container-fluid p-5 min-vh-100 d-inline-block justify-content-center">
  <h3>Projects</h3>
    {% for project in latest_project_list %}
    <div class="row mb-2 px-5">
      <div class="card m-auto col">
        <div class="card-header">
          <p class="card-text status">{{ project.outcome }}</p>
        </div>
        <div class="card-body">
          <h5 class="card-title"> {{ project }} </h5>
          <p class="card-text description">{{ project.short_description }}</p>
          <p class="card-text timeline">{{ project.timeline }}</p>
          <a href="{% url 'portfoilo:project' project.project_shortname %}" class="btn btn-primary">View Details</a>
        </div>
        <div class="card-footer text-muted">
          <p class="card-text languages">{{ project.languages }}</p>
        </div>
      </div>
    </div>
    {% endfor %}
</div>
<div id="resume" class="p-4" style="width:100%; height:10px;"></div>
<div class="container p-5 min-vh-100 d-inline-block">
  <h3>Resume</h3>
  <h5>Skills</h5>
  <div class="row px-5 mb-4">
    <ul>
      <li>Programming/ scripting languages: C++, C#, JavaScript, HTML, CSS, PHP, R, Python, SQL</li>
      <li>Frameworks/ Libraries: SCSS, Node.js, Tidyverse, Pandas, Numpy, Dash, Django</li>
      <li>Other development tools: Linux CLI, Docker, Git, AWS (basics)</li>
    </ul>
  </div>
  <h5>Education</h5>
  <div class="row px-5 mb-4">
    <div class="col-sm-auto degree">
      <p class="name">Masters of Science in Computer Science</p>
      <p class="concentration">Data Analytics</p>
      <p class="school">Boston University</p>
    </div>
    <div class="col-sm-auto degree">
      <p class="name">Bachelor of Arts in Sociology</p>
      <p class="concentration">Queer Studies</p>
      <p class="school">Boston University</p>
    </div>
  </div>
  <h5>Work History</h5>
  {% for job in jobs %}
  <div class="row px-5 mb-2 resume_block">
    <p class="title">{{ job }} (<span class="dates">
      {{ job.start_date }}
      {% if job.current_job %}
      - Present
      {% else %}
      - {{ job.end_date }}
      {% endif %}
    </span>)</p>
    <p class="company">{{ job.company }} | <span class="department">{{ job.department }}</span></p>
    <ul class="px-5">
      {% for responsibility in responsibilities %}
        {% if job == responsibility.job %}
          <li>{{ responsibility }}</li>
        {% endif %}
      {% endfor %}
    </ul>
  </div>
  {% endfor %}
</div>
{% endblock %}

Portfolio/portfolio/templates/portfolio/project.html
{% extends "base.html" %}

{% load static %}

{% block title %}{{ project.project_name }}{% endblock %}

{% block content %}
    <h1>{{ project.project_name }}</h1>
    <p> {{ project.description|linebreaks }}</p>
{% endblock %}
    
    
    

Portfolio/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Olivia McCargar | Portfolio{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'libs/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/style/style.css' %}">
    {% block stylesheets %}
    {% endblock %}
  </head>
  <body {% block bodyclasses %}{% endblock %} >
    {% block content %}{% endblock %}
    <script src="{% static 'libs/jquery/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'libs/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'portfolio/script/portfolio.js' %}"></script>
    {% block scripts %}
    {% endblock %}
    <div class="container">
      <footer class="py-3 my-4">
        <p class="text-center text-muted">Updated September 2022 Olivia McCargar</p>
      </footer>
    </div>
  </body>
</html>